/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatorioIdRouteImport } from './routes/relatorio.$id'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprarRouteImport } from './routes/_authenticated/comprar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as TesteIdSalasRouteImport } from './routes/teste.$id.salas'
import { Route as TesteIdIntroRouteImport } from './routes/teste.$id.intro'
import { Route as TesteIdConcluidoRouteImport } from './routes/teste.$id.concluido'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin/vendedores'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSalasRouteImport } from './routes/_authenticated/admin/salas'
import { Route as AuthenticatedAdminComissoesRouteImport } from './routes/_authenticated/admin/comissoes'
import { Route as AuthenticatedAdminSalasIndexRouteImport } from './routes/_authenticated/admin/salas.index'
import { Route as TesteIdSalaSlugRouteImport } from './routes/teste.$id.sala.$slug'
import { Route as TesteIdSalaConcluidaSlugRouteImport } from './routes/teste.$id.sala-concluida.$slug'
import { Route as AuthenticatedTestesIdDestinatarioRouteImport } from './routes/_authenticated/testes.$id.destinatario'
import { Route as AuthenticatedAdminVendedoresNovoRouteImport } from './routes/_authenticated/admin/vendedores.novo'
import { Route as AuthenticatedAdminVendedoresCodeRouteImport } from './routes/_authenticated/admin/vendedores.$code'
import { Route as AuthenticatedAdminSalasNovaRouteImport } from './routes/_authenticated/admin/salas.nova'
import { Route as AuthenticatedAdminSalasIdRouteImport } from './routes/_authenticated/admin/salas.$id'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioIdRoute = RelatorioIdRouteImport.update({
  id: '/relatorio/$id',
  path: '/relatorio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprarRoute = AuthenticatedComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const TesteIdSalasRoute = TesteIdSalasRouteImport.update({
  id: '/teste/$id/salas',
  path: '/teste/$id/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIdIntroRoute = TesteIdIntroRouteImport.update({
  id: '/teste/$id/intro',
  path: '/teste/$id/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIdConcluidoRoute = TesteIdConcluidoRouteImport.update({
  id: '/teste/$id/concluido',
  path: '/teste/$id/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/vendedores',
    path: '/vendedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalasRoute = AuthenticatedAdminSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminComissoesRoute =
  AuthenticatedAdminComissoesRouteImport.update({
    id: '/comissoes',
    path: '/comissoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalasIndexRoute =
  AuthenticatedAdminSalasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSalasRoute,
  } as any)
const TesteIdSalaSlugRoute = TesteIdSalaSlugRouteImport.update({
  id: '/teste/$id/sala/$slug',
  path: '/teste/$id/sala/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIdSalaConcluidaSlugRoute =
  TesteIdSalaConcluidaSlugRouteImport.update({
    id: '/teste/$id/sala-concluida/$slug',
    path: '/teste/$id/sala-concluida/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTestesIdDestinatarioRoute =
  AuthenticatedTestesIdDestinatarioRouteImport.update({
    id: '/testes/$id/destinatario',
    path: '/testes/$id/destinatario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVendedoresNovoRoute =
  AuthenticatedAdminVendedoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminVendedoresRoute,
  } as any)
const AuthenticatedAdminVendedoresCodeRoute =
  AuthenticatedAdminVendedoresCodeRouteImport.update({
    id: '/$code',
    path: '/$code',
    getParentRoute: () => AuthenticatedAdminVendedoresRoute,
  } as any)
const AuthenticatedAdminSalasNovaRoute =
  AuthenticatedAdminSalasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedAdminSalasRoute,
  } as any)
const AuthenticatedAdminSalasIdRoute =
  AuthenticatedAdminSalasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSalasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/comprar': typeof AuthenticatedComprarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/admin/salas': typeof AuthenticatedAdminSalasRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/teste/$id/concluido': typeof TesteIdConcluidoRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/salas/$id': typeof AuthenticatedAdminSalasIdRoute
  '/admin/salas/nova': typeof AuthenticatedAdminSalasNovaRoute
  '/admin/vendedores/$code': typeof AuthenticatedAdminVendedoresCodeRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/testes/$id/destinatario': typeof AuthenticatedTestesIdDestinatarioRoute
  '/teste/$id/sala-concluida/$slug': typeof TesteIdSalaConcluidaSlugRoute
  '/teste/$id/sala/$slug': typeof TesteIdSalaSlugRoute
  '/admin/salas/': typeof AuthenticatedAdminSalasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/teste/$id/concluido': typeof TesteIdConcluidoRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/salas/$id': typeof AuthenticatedAdminSalasIdRoute
  '/admin/salas/nova': typeof AuthenticatedAdminSalasNovaRoute
  '/admin/vendedores/$code': typeof AuthenticatedAdminVendedoresCodeRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/testes/$id/destinatario': typeof AuthenticatedTestesIdDestinatarioRoute
  '/teste/$id/sala-concluida/$slug': typeof TesteIdSalaConcluidaSlugRoute
  '/teste/$id/sala/$slug': typeof TesteIdSalaSlugRoute
  '/admin/salas': typeof AuthenticatedAdminSalasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/comprar': typeof AuthenticatedComprarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/_authenticated/admin/comissoes': typeof AuthenticatedAdminComissoesRoute
  '/_authenticated/admin/salas': typeof AuthenticatedAdminSalasRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/teste/$id/concluido': typeof TesteIdConcluidoRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/salas/$id': typeof AuthenticatedAdminSalasIdRoute
  '/_authenticated/admin/salas/nova': typeof AuthenticatedAdminSalasNovaRoute
  '/_authenticated/admin/vendedores/$code': typeof AuthenticatedAdminVendedoresCodeRoute
  '/_authenticated/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/_authenticated/testes/$id/destinatario': typeof AuthenticatedTestesIdDestinatarioRoute
  '/teste/$id/sala-concluida/$slug': typeof TesteIdSalaConcluidaSlugRoute
  '/teste/$id/sala/$slug': typeof TesteIdSalaSlugRoute
  '/_authenticated/admin/salas/': typeof AuthenticatedAdminSalasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/relatorios'
    | '/admin'
    | '/comprar'
    | '/dashboard'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/admin/comissoes'
    | '/admin/salas'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/teste/$id/concluido'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/admin/'
    | '/admin/salas/$id'
    | '/admin/salas/nova'
    | '/admin/vendedores/$code'
    | '/admin/vendedores/novo'
    | '/testes/$id/destinatario'
    | '/teste/$id/sala-concluida/$slug'
    | '/teste/$id/sala/$slug'
    | '/admin/salas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/relatorios'
    | '/comprar'
    | '/dashboard'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/admin/comissoes'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/teste/$id/concluido'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/admin'
    | '/admin/salas/$id'
    | '/admin/salas/nova'
    | '/admin/vendedores/$code'
    | '/admin/vendedores/novo'
    | '/testes/$id/destinatario'
    | '/teste/$id/sala-concluida/$slug'
    | '/teste/$id/sala/$slug'
    | '/admin/salas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/relatorios'
    | '/_authenticated/admin'
    | '/_authenticated/comprar'
    | '/_authenticated/dashboard'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/_authenticated/admin/comissoes'
    | '/_authenticated/admin/salas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vendedores'
    | '/teste/$id/concluido'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/salas/$id'
    | '/_authenticated/admin/salas/nova'
    | '/_authenticated/admin/vendedores/$code'
    | '/_authenticated/admin/vendedores/novo'
    | '/_authenticated/testes/$id/destinatario'
    | '/teste/$id/sala-concluida/$slug'
    | '/teste/$id/sala/$slug'
    | '/_authenticated/admin/salas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  RelatorioIdRoute: typeof RelatorioIdRoute
  TesteIdConcluidoRoute: typeof TesteIdConcluidoRoute
  TesteIdIntroRoute: typeof TesteIdIntroRoute
  TesteIdSalasRoute: typeof TesteIdSalasRoute
  TesteIdSalaConcluidaSlugRoute: typeof TesteIdSalaConcluidaSlugRoute
  TesteIdSalaSlugRoute: typeof TesteIdSalaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$id': {
      id: '/relatorio/$id'
      path: '/relatorio/$id'
      fullPath: '/relatorio/$id'
      preLoaderRoute: typeof RelatorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comprar': {
      id: '/_authenticated/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof AuthenticatedComprarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/teste/$id/salas': {
      id: '/teste/$id/salas'
      path: '/teste/$id/salas'
      fullPath: '/teste/$id/salas'
      preLoaderRoute: typeof TesteIdSalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/$id/intro': {
      id: '/teste/$id/intro'
      path: '/teste/$id/intro'
      fullPath: '/teste/$id/intro'
      preLoaderRoute: typeof TesteIdIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/$id/concluido': {
      id: '/teste/$id/concluido'
      path: '/teste/$id/concluido'
      fullPath: '/teste/$id/concluido'
      preLoaderRoute: typeof TesteIdConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salas': {
      id: '/_authenticated/admin/salas'
      path: '/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AuthenticatedAdminSalasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comissoes': {
      id: '/_authenticated/admin/comissoes'
      path: '/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AuthenticatedAdminComissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/salas/': {
      id: '/_authenticated/admin/salas/'
      path: '/'
      fullPath: '/admin/salas/'
      preLoaderRoute: typeof AuthenticatedAdminSalasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSalasRoute
    }
    '/teste/$id/sala/$slug': {
      id: '/teste/$id/sala/$slug'
      path: '/teste/$id/sala/$slug'
      fullPath: '/teste/$id/sala/$slug'
      preLoaderRoute: typeof TesteIdSalaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/$id/sala-concluida/$slug': {
      id: '/teste/$id/sala-concluida/$slug'
      path: '/teste/$id/sala-concluida/$slug'
      fullPath: '/teste/$id/sala-concluida/$slug'
      preLoaderRoute: typeof TesteIdSalaConcluidaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/testes/$id/destinatario': {
      id: '/_authenticated/testes/$id/destinatario'
      path: '/testes/$id/destinatario'
      fullPath: '/testes/$id/destinatario'
      preLoaderRoute: typeof AuthenticatedTestesIdDestinatarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vendedores/novo': {
      id: '/_authenticated/admin/vendedores/novo'
      path: '/novo'
      fullPath: '/admin/vendedores/novo'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminVendedoresRoute
    }
    '/_authenticated/admin/vendedores/$code': {
      id: '/_authenticated/admin/vendedores/$code'
      path: '/$code'
      fullPath: '/admin/vendedores/$code'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresCodeRouteImport
      parentRoute: typeof AuthenticatedAdminVendedoresRoute
    }
    '/_authenticated/admin/salas/nova': {
      id: '/_authenticated/admin/salas/nova'
      path: '/nova'
      fullPath: '/admin/salas/nova'
      preLoaderRoute: typeof AuthenticatedAdminSalasNovaRouteImport
      parentRoute: typeof AuthenticatedAdminSalasRoute
    }
    '/_authenticated/admin/salas/$id': {
      id: '/_authenticated/admin/salas/$id'
      path: '/$id'
      fullPath: '/admin/salas/$id'
      preLoaderRoute: typeof AuthenticatedAdminSalasIdRouteImport
      parentRoute: typeof AuthenticatedAdminSalasRoute
    }
  }
}

interface AuthenticatedAdminSalasRouteChildren {
  AuthenticatedAdminSalasIdRoute: typeof AuthenticatedAdminSalasIdRoute
  AuthenticatedAdminSalasNovaRoute: typeof AuthenticatedAdminSalasNovaRoute
  AuthenticatedAdminSalasIndexRoute: typeof AuthenticatedAdminSalasIndexRoute
}

const AuthenticatedAdminSalasRouteChildren: AuthenticatedAdminSalasRouteChildren =
  {
    AuthenticatedAdminSalasIdRoute: AuthenticatedAdminSalasIdRoute,
    AuthenticatedAdminSalasNovaRoute: AuthenticatedAdminSalasNovaRoute,
    AuthenticatedAdminSalasIndexRoute: AuthenticatedAdminSalasIndexRoute,
  }

const AuthenticatedAdminSalasRouteWithChildren =
  AuthenticatedAdminSalasRoute._addFileChildren(
    AuthenticatedAdminSalasRouteChildren,
  )

interface AuthenticatedAdminVendedoresRouteChildren {
  AuthenticatedAdminVendedoresCodeRoute: typeof AuthenticatedAdminVendedoresCodeRoute
  AuthenticatedAdminVendedoresNovoRoute: typeof AuthenticatedAdminVendedoresNovoRoute
}

const AuthenticatedAdminVendedoresRouteChildren: AuthenticatedAdminVendedoresRouteChildren =
  {
    AuthenticatedAdminVendedoresCodeRoute:
      AuthenticatedAdminVendedoresCodeRoute,
    AuthenticatedAdminVendedoresNovoRoute:
      AuthenticatedAdminVendedoresNovoRoute,
  }

const AuthenticatedAdminVendedoresRouteWithChildren =
  AuthenticatedAdminVendedoresRoute._addFileChildren(
    AuthenticatedAdminVendedoresRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminComissoesRoute: typeof AuthenticatedAdminComissoesRoute
  AuthenticatedAdminSalasRoute: typeof AuthenticatedAdminSalasRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminComissoesRoute: AuthenticatedAdminComissoesRoute,
  AuthenticatedAdminSalasRoute: AuthenticatedAdminSalasRouteWithChildren,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVendedoresRoute:
    AuthenticatedAdminVendedoresRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedComprarRoute: typeof AuthenticatedComprarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTestesIdDestinatarioRoute: typeof AuthenticatedTestesIdDestinatarioRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedComprarRoute: AuthenticatedComprarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTestesIdDestinatarioRoute:
    AuthenticatedTestesIdDestinatarioRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  RelatorioIdRoute: RelatorioIdRoute,
  TesteIdConcluidoRoute: TesteIdConcluidoRoute,
  TesteIdIntroRoute: TesteIdIntroRoute,
  TesteIdSalasRoute: TesteIdSalasRoute,
  TesteIdSalaConcluidaSlugRoute: TesteIdSalaConcluidaSlugRoute,
  TesteIdSalaSlugRoute: TesteIdSalaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
