/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatorioIdRouteImport } from './routes/relatorio.$id'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as TestesIdDestinatarioRouteImport } from './routes/testes.$id.destinatario'
import { Route as TesteIdSalasRouteImport } from './routes/teste.$id.salas'
import { Route as TesteIdIntroRouteImport } from './routes/teste.$id.intro'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioIdRoute = RelatorioIdRouteImport.update({
  id: '/relatorio/$id',
  path: '/relatorio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesIdDestinatarioRoute = TestesIdDestinatarioRouteImport.update({
  id: '/testes/$id/destinatario',
  path: '/testes/$id/destinatario',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIdSalasRoute = TesteIdSalasRouteImport.update({
  id: '/teste/$id/salas',
  path: '/teste/$id/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const TesteIdIntroRoute = TesteIdIntroRouteImport.update({
  id: '/teste/$id/intro',
  path: '/teste/$id/intro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comprar': typeof ComprarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/testes/$id/destinatario': typeof TestesIdDestinatarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comprar': typeof ComprarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/testes/$id/destinatario': typeof TestesIdDestinatarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/comprar': typeof ComprarRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/relatorio/$id': typeof RelatorioIdRoute
  '/teste/$id/intro': typeof TesteIdIntroRoute
  '/teste/$id/salas': typeof TesteIdSalasRoute
  '/testes/$id/destinatario': typeof TestesIdDestinatarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/comprar'
    | '/dashboard'
    | '/login'
    | '/relatorios'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/testes/$id/destinatario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/comprar'
    | '/dashboard'
    | '/login'
    | '/relatorios'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/testes/$id/destinatario'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/comprar'
    | '/dashboard'
    | '/login'
    | '/relatorios'
    | '/convite/$token'
    | '/relatorio/$id'
    | '/teste/$id/intro'
    | '/teste/$id/salas'
    | '/testes/$id/destinatario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComprarRoute: typeof ComprarRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  RelatorioIdRoute: typeof RelatorioIdRoute
  TesteIdIntroRoute: typeof TesteIdIntroRoute
  TesteIdSalasRoute: typeof TesteIdSalasRoute
  TestesIdDestinatarioRoute: typeof TestesIdDestinatarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$id': {
      id: '/relatorio/$id'
      path: '/relatorio/$id'
      fullPath: '/relatorio/$id'
      preLoaderRoute: typeof RelatorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes/$id/destinatario': {
      id: '/testes/$id/destinatario'
      path: '/testes/$id/destinatario'
      fullPath: '/testes/$id/destinatario'
      preLoaderRoute: typeof TestesIdDestinatarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/$id/salas': {
      id: '/teste/$id/salas'
      path: '/teste/$id/salas'
      fullPath: '/teste/$id/salas'
      preLoaderRoute: typeof TesteIdSalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teste/$id/intro': {
      id: '/teste/$id/intro'
      path: '/teste/$id/intro'
      fullPath: '/teste/$id/intro'
      preLoaderRoute: typeof TesteIdIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComprarRoute: ComprarRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  RelatorioIdRoute: RelatorioIdRoute,
  TesteIdIntroRoute: TesteIdIntroRoute,
  TesteIdSalasRoute: TesteIdSalasRoute,
  TestesIdDestinatarioRoute: TestesIdDestinatarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
